# Generated by Django 2.2.5 on 2019-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190909_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
    ]
