# Generated by Django 2.2.5 on 2019-09-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0004_remove_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(default=1243, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
            preserve_default=False,
        ),
    ]
