# Generated by Django 2.2.5 on 2019-09-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
